language: dart
sudo: false
dart:
- stable
with_content_shell: false
dart_task:
- dartanalyzer: --fatal-warnings lib
- dartfmt
script:
  - set -e
  - pub run test test/redux_thunk_test.dart
  - pub get
  - pub run test test/redux_thunk_test.dart --coverage=coverage
  - pub global activate coverage
  - pub global run coverage:format_coverage --in coverage/test/redux_thunk_test.dart.vm.json --out lcov.info --lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
