name: redux_thunk
author: Brian Egan <brian@brianegan.com>
description: A Redux.dart Middleware that allows you to dispatch functions that perform async work as actions.
homepage: https://github.com/brianegan/redux_thunk
version: 0.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  redux: ">=4.0.0 <5.0.0"

dev_dependencies:
  test: 1.9.4
  pedantic: 1.8.0+1

