name: redux_thunk
author: Brian Egan <brian@brianegan.com>
description: A Redux.dart Middleware that allows you to dispatch functions that perform async work as actions.
homepage: https://github.com/brianegan/redux_thunk
version: 0.3.99-atreeonnullsafety2

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  redux: ^5.0.0

dev_dependencies:
  test: ^1.16.0-nullsafety.16
  pedantic: 1.10.0-nullsafety.3

